appName: wafi-app
appImage: root0877/wafi_app
appVersion: latest
appReplicas: 1
containerPort: 8000
containerEnvVars:
- name: ENV_VAR_ONE
  value: "valueone"
- name: ENV_VAR_TWO
  value: "valuetwo"  

servicePort: 80
serviceType: LoadBalancer