apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: app
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}
