apiVersion: apps/v1
kind: Deployment
metadata:
  name: wafi-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wafi-app
  template:
    metadata:
      labels:
        app: wafi-app
    spec:
      containers:
      - name: wafi-app
        image: root0877/wafi_app:latest
        ports:
        - containerPort: 8000


