apiVersion: v1
kind: Service
metadata:
  name: wafi-app-service
  namespace: app
spec:
  selector:
    app: wafi-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
