name: Deploy to wafi Kubernetes cluster 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure Docker
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t root0877/wafi_app:latest .
        docker push root0877/wafi_app:latest

